apiVersion: networking.k8s.io/v1 #stable
kind: Ingress #config file for ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/default-backend: app-three #default
spec:
  rules:
  - host: app1.com #if header app1.com
    http:
      paths:
      - path: / #starts with / (true)
        pathType: Prefix #starts with (app1/xxx will work)
        backend:
          service:
            name: app-one #forward to service app-one on port 80
            port:
              number: 80
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-two
            port:
              number: 80
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three
            port:
              number: 80
  - http: #big fat else, route to app3 if no match
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three
            port:
              number: 80
